export const STAGE_MESSAGE_TYPE = 'STAGE';
export const ANSWER_MESSAGE_TYPE = 'ANSWER';
export const VOTE_MESSAGE_TYPE = 'VOTE';
export const PUBLIC_MESSAGE_TYPE = 'PUBLIC';
export const PERSONAL_MESSAGE_TYPE = 'PERSONAL';
export const NEXT_QUESTION_MESSAGE_TYPE = 'NEXT_QUESTION';

export const PUBLIC_QUESTION_STAGE = 'PUBLIC_QUESTION';
export const PERSONAL_QUESTION_STAGE = 'PERSONAL_QUESTION';
export const VOTING_STAGE = 'VOTING';
export const RESULTS_STAGE = 'RESULTS';

export const POINTS_FOR_TRUTH = 50;
export const POINTS_FOR_LYING = 50;

export const PLAYER_MASK = '<&>';
