FROM node:alpine

WORKDIR /server

EXPOSE 3002

ENV REACT_APP_COLYSEUS_URL=ws://game-server.azurewebsites.net
ENV REACT_APP_CLIENT_URL=https://de-la-cringe.azurewebsites.net

COPY package*.json ./
RUN npm i --force
COPY . . 

CMD ["npm", "start"]
