POST http://192.168.1.152:3002/api/users/signInAccount
Content-Type: application/json

{
  "username": "DanLuk",
  "password": "12345qwertyQ/"
}

###

POST http://localhost:3002/api/users/createAccount
Content-Type: application/json

{
  "username": "DanLuk",
  "password": "12345qwertyQ/"
}


###

GET http://localhost:3002/api/users/isAuthorized

###

GET http://localhost:3002/api/users/logoutFromAccount

###

GET http://localhost:3002/files/buttons/BuyButton.svg