POST http://localhost:3002/api/users/signInAccount
Content-Type: application/json

{
  "username": "Dan",
  "password": "12345qw$eQrty"
}

###

GET http://localhost:3002/api/users/getUserInfo

###

GET http://localhost:3002/api/users/logoutFromAccount